### ISSUE TITLE
Tutorials

### ISSUE THREAD

**Issue by mixmixmix** [road86/bahis-infra#1]
1. Simple Docker with python in it:
https://github.com/road86/bahis-infra/tree/6bdf1cebb44db4d8c715d580add3cc4d12095a96

2. Simple dockerfile nginx uwsgi python web
https://github.com/road86/bahis-infra/tree/6c7b963194593cd845ecb02165bc8458bb2758c4

3. Simple docker for Django+uwsgi
https://github.com/road86/bahis-infra/tree/5bb4d20a9d59a889255e45e71d7b815f855c918a/test/nupd_infra/djangoapp

4. Just a postgres using docker:
https://github.com/road86/bahis-infra/blob/master/test/justdb/docker-compose.yml

5. Simple docker for Django+uwsgi+postgres:
https://github.com/road86/bahis-infra/tree/815d309b8a153b4b5b628c73906ec95481ebf857/test/nupd_infra

6. Django, uwsgi, nginx, postgres:
https://github.com/road86/bahis-infra/tree/22f8d738cfadc7e4693df33a37c1a4d64bb5b97e/test/nupd_infra

**Comment by ChasNelson1990** [comment]
@mixmixmix - I would like to move this out of issues (as it isn't a resolvable ticket). Can you think of an alternative place for these to go? I'm not sure the readme is the correct place either, also they will be less important moving forward though as our infrastructure will be more closely aligned to kobo-docker. Perhaps we just close this?

**Comment by mixmixmix** [comment]
Fine to close that, can be found in closed issues if needed.
