### ISSUE TITLE
Provide a subpage url for dashboard in nginx

### ISSUE THREAD

**Issue by mixmixmix** [road86/bahis-infra#16]
### Problem

Our dashboard(s) are running on different ports of an IP address. That means that I cannot connect a subdomain to them directly.

### Desired Solution

As far as I can tell, we can use nginx to redirect anywahere we like. 

It would be great if we can have a `bahis2-dev.net/dash` as an address for our main dashboard.

**Comment by shaarful** [comment]
Thanks, @mixmixmix. Let me do that on my local machine.

**Comment by ChasNelson1990** [comment]
Can this be closed now?

**Comment by mixmixmix** [comment]
I don't think it is yet resolved and we need it.

**Comment by ChasNelson1990** [comment]
@sharful09 can we get an update then please?

**Comment by ChasNelson1990** [comment]
@shaarful can this be closed :confused:

**Comment by shaarful** [comment]
> @shaarful can this be closed 😕

yes we can close this.
