### ISSUE TITLE
Provide a docker config for bahis-data and bahis-dash

### ISSUE THREAD

**Issue by mixmixmix** [road86/bahis-infra#20]
### Problem

We need to be able to deploy using docker

### Desired Solution

Ultimatelly it will be in a same docker-compose file as the rest of the bahis setup but we are starting and making it work on its own

**Comment by ChasNelson1990** [comment]
Relates #16?

**Comment by mixmixmix** [comment]
@sharful09, I'm still working on it, I didn't manage to finish today but will try to get it for you asap...

**Comment by shaarful** [comment]
> @sharful09, I'm still working on it, I didn't manage to finish today but will try to get it for you asap...

Noted Miks. Let me know when you will be done.

**Comment by mixmixmix** [comment]
@sharful09 ready for your testing: https://github.com/road86/bahis-infra/pull/22 I'm sending necessary files via slack.
